# Generated by Django 2.2 on 2020-01-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='granted_by',
        ),
    ]
